replicaCount: 1
image:
  repository: centrifugo/centrifugo
  tag: 1.7.3
  pullPolicy: IfNotPresent
service:
  name: http
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000

## Ingress configuration.
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false

  ## Hostnames.
  ## Must be provided if Ingress is enabled.
  ##
  # hosts:
  #   - centrifugo.local

  ## Annotations.
  ##
  #  annotations:
  #    kubernetes.io/ingress.class: nginx
  #    ingress.kubernetes.io/upstream-fail-timeout: 60
  #    ingress.kubernetes.io/upstream-max-fails: 2
  #    ingress.kubernetes.io/proxy-read-timeout: 3600
  #    ingress.kubernetes.io/proxy-send-timeout: 3600
  #
  #    If you use https://github.com/nginxinc/kubernetes-ingress add next annotation
  #    to enable websockets:
  #    nginx.org/websocket-services: centrifugo-centrifugo
  #

  ## TLS configuration.
  ## Secrets must be manually created in the namespace.
  ##
  # tls:
  #   - secretName: centrifugo-tls
  #     hosts:
  #       - centrifugo.local

config:
  secret: secret
  web: true
  admin_password: password
  admin_secret: secret
  namespaces:
  - name: public
    anonymous: true
    publish: true
    watch: true
    presence: true
    join_leave: true
    history_size: 10
    history_lifetime: 30
    recover: true

args:
  - --web=true

resources: {}
